title: Attrition Avoidance
description: An end-to-end Machine Learning Pipeline encompassing identification, reasoning, and avoidance of attrition amongst employees.
theme: just-the-docs
#remote_theme: pmarsceill/just-the-docs
